name: focusflow
description: A local-first distraction-free productivity MVP for students.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^4.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
